// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAQQ_LQmv6aSbp8B88IPKis6LSI8KIbVc',
    appId: '1:38288416449:web:07576a7b039d0793d4be40',
    messagingSenderId: '38288416449',
    projectId: 'social-media-flutter-79f72',
    authDomain: 'social-media-flutter-79f72.firebaseapp.com',
    storageBucket: 'social-media-flutter-79f72.appspot.com',
    measurementId: 'G-Q9XYLNR13K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8PTWWQ6Ft2Ji-gxw5SjqPvk76_Gp4N0U',
    appId: '1:38288416449:android:b23f56904fbb0b43d4be40',
    messagingSenderId: '38288416449',
    projectId: 'social-media-flutter-79f72',
    storageBucket: 'social-media-flutter-79f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFxikiQ5P5Eb4Sbyw8ClcBzCic2a5W3TY',
    appId: '1:38288416449:ios:114a2af624a47005d4be40',
    messagingSenderId: '38288416449',
    projectId: 'social-media-flutter-79f72',
    storageBucket: 'social-media-flutter-79f72.appspot.com',
    iosBundleId: 'com.example.googlemaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFxikiQ5P5Eb4Sbyw8ClcBzCic2a5W3TY',
    appId: '1:38288416449:ios:114a2af624a47005d4be40',
    messagingSenderId: '38288416449',
    projectId: 'social-media-flutter-79f72',
    storageBucket: 'social-media-flutter-79f72.appspot.com',
    iosBundleId: 'com.example.googlemaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAQQ_LQmv6aSbp8B88IPKis6LSI8KIbVc',
    appId: '1:38288416449:web:544ed86edcd59b68d4be40',
    messagingSenderId: '38288416449',
    projectId: 'social-media-flutter-79f72',
    authDomain: 'social-media-flutter-79f72.firebaseapp.com',
    storageBucket: 'social-media-flutter-79f72.appspot.com',
    measurementId: 'G-29MP2517F5',
  );
}
